services:
  - type: web
    name: driveledger-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn eld_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: eld_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: render.com
      - key: RENDER
        value: TRUE