# Generated by Django 5.2.6 on 2025-09-18 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startMin', models.IntegerField()),
                ('endMin', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='eld_api.driverlogday')),
            ],
        ),
    ]
